### ISSUE TITLE
Config file missing after install

### ISSUE THREAD

**Issue by seanthegeek** [rieck/malheur#13]
When I tried to run `malheur` 0.5.4 after installing it from source on Ubuntu 14.04 LTS, I got:

    Error: Could not open file '/usr/local/var/malheur/malheur.cfg'.: Permission denied [copy_file]
    Error: Could not read configuration (file I/O error in line 0): No such file or directory [load_config]

The file `/usr/local/var/malheur/malheur.cfg` doesn't exist. Shouldn't a default configuration come with the install? If not, how can I create it?

**Comment by rieck** [comment]
Did you run `make install` with permission to write to `/usr/local`?

**Comment by seanthegeek** [comment]
I originally used `sudo checkinstall` to make and and install a deb package out of it. When I noticed that the config file was missing, I tried `sudo make install` with the same results.

**Comment by rieck** [comment]
This is likely a permission issue that you can fix with `chown` and `chmod`. 

I am currently working on improving this setup.

**Comment by seanthegeek** [comment]
Yes.

$ ls -al /usr/local/var/malheur/
total 8
drwxr-xr-x 2 root root 4096 Aug 25 11:48 .
drwxr-xr-x 3 root root 4096 Aug 24 20:06 ..

After I changed the group and permissions of `/usr/local/var/malheur/`, `malhur` wrote the needed config file on the next run.
