### ISSUE TITLE
Mac Install Error - argz.m4

### ISSUE THREAD

**Issue by peasead** [rieck/malheur#18]
aclocal: error: aclocal: file '/usr/local/share/aclocal/argz.m4' does not exist

Run `brew doctor` and then `brew prune`

**Comment by rieck** [comment]
Is this a `homebrew` issue?

**Comment by peasead** [comment]
I think it is a `homebrew` issue, but the fix is run `brew doctor` and `brew prune`.

**Comment by rieck** [comment]
okay. marking as closed.
