### ISSUE TITLE
malheur.h.in is missing

### ISSUE THREAD

**Issue by cjmateos** [rieck/malheur#21]
Hi team,

I've noticed that after a "make clean" the file "malheur.h" is removed. This file must be dinamically created in the compilation process, but the file "malheur.h.in" is missing. Then it's not possible to build the code after run "make clean". First time I try to build the code it runs fine because "malheur.h" is downloaded from the repo.

Regards

**Comment by rieck** [comment]
Thanks for pointing out this bug.
