### ISSUE TITLE
Specify Machine Learning Algorithms ?

### ISSUE THREAD

**Issue by nighatusman03** [rieck/malheur#22]
Hi I want to apply Naive Bayes classification technique on cuckoo reports via Malheur Malware Analysis. For that I want to get information about Malheur's classification technique which is already enabled in it. Which classification technique is coded in malheur ?
Thanks in advance for valuable answers..

**Comment by rieck** [comment]
What are you trying to do? Note that Malheur has not been designed for malware detection. 

The tool allows to cluster malware behaviour into similar groups and classify unknown behaviour to these clusters. The tool uses a variant of kNN denoted  as _nearest-prototype classification_ for the last step.

**Comment by nighatusman03** [comment]
Yeah i know that malheur is not for malware detection, actually i want to apply naive bayes algorithm on cuckoo's report. So, is naive bayes algorithm is coded in malheur or can i modify malheur.py?

**Comment by rieck** [comment]
Naive Bayes classification is not part of Malheur. Note also that Malheur is not written in Python.

**Comment by nighatusman03** [comment]
ok thanks for helping me out.
