### ISSUE TITLE
reports of malware behavior

### ISSUE THREAD

**Issue by wswhorse** [rieck/malheur#8]
I want to know that whether the Malheur contains the function can gain the reports of malware behavior if I have some new samples.

**Comment by rieck** [comment]
Malheur is not a malware sandbox. Instead the tool aims at analyzing the output of malware sandboxes.

**Comment by wswhorse** [comment]
OK~I just want to know the format of the reports .Whether I can use the original XML representation of CWSandbox as input,or I must change the original XML with MIST.
